### ISSUE TITLE
Add to CIMAS

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-lutaml#102]
Add this gem to cimas. Also add: metanorma-plugin-datastruct , metanorma-plugin-glossarist

**Comment by opoudjis** [comment]
I could not get Gemfile.devel behaviour for these gems, I added Gemfile.devel call to Gemfile manually: https://github.com/metanorma/metanorma-plugin-lutaml/commit/b8fe69ad98e3ec69d905a384f80e20fd6dd5dee5

Presumably that means CIMAS needs to be updated?

**Comment by ronaldtse** [comment]
@CAMOBAP can you help here? Thanks!
