### ISSUE TITLE
spec breaking on invalid URIs

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-lutaml#117]
https://github.com/metanorma/metanorma-plugin-lutaml/actions/runs/9640683586/job/26584966393

This is now also breaking metanorma-standoc, since it has the same test.

Gems **MUST NOT BE RELEASED** if they are breaking testing. This is now breaking the Metanorma stack, which is a downstream consumer of this gem as infrastructure. Testing **MUST BE TAKEN SERIOUSLY** in Metanorma infrastructure development.

**Comment by CAMOBAP** [comment]
> @CAMOBAP this has been breaking standoc on GHA for days, you should be being notified on it.

At the moment I just added workflows to run, @ronaldtse could you please add me to mailing lists for isodoc, metanorma-iso and metanorma-standoc so I get all notifications related to GHA

**Comment by opoudjis** [comment]
> > @CAMOBAP this has been breaking standoc on GHA for days, you should be being notified on it.
> 
> At the moment I just added workflows to run, @ronaldtse could you please add me to mailing lists for isodoc, metanorma-iso and metanorma-standoc so I get all notifications related to GHA

I haven't been getting notifications, FWIW, but the integration job ran on standoc for the first time today (after I pushed the test disable).

**Comment by kwkwan** [comment]
@opoudjis Some tests are rewriting to reflect the changes in xmi.

**Comment by ronaldtse** [comment]
The relevant task is here:
* https://github.com/lutaml/xmi/issues/25
