### ISSUE TITLE
Provide command to render an Enterprise Architect diagram from XMI

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#121]
From:
* https://github.com/metanorma/metanorma-plugin-lutaml/issues/120

For:
* https://github.com/metanorma/mn-samples-plateau/pull/114

In Enterprise Architect, it is possible to copy out the "Node Path" from a diagram ("Node Path To Clipboard"):
<img width="563" alt="Screenshot 2024-07-13 at 10 43 57 AM" src="https://github.com/user-attachments/assets/076e9f39-90b8-4987-89ec-3d99f8255c49">

```
Conceptual Models.3D都市モデル.3D 都市モデル.4.2.2_2_1
```

## Command to include a diagram only

```adoc
// 4.2.2 (2) 1)
lutaml_ea_diagram::file.xmi[address="Conceptual Models.3D都市モデル.3D 都市モデル.4.2.2_2_1",base_path="./xmi-images",format="png"]
```

**Comment by kwkwan** [comment]
Closed as completed in https://github.com/metanorma/metanorma-plugin-lutaml/pull/128.
