### ISSUE TITLE
`lutaml_uml_datamodel_description` unable to recurse into sub-packages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#123]
This relates to:
* https://github.com/metanorma/mn-samples-plateau/issues/114

And the XMI is available there.

My command is:
```adoc
[lutaml_uml_datamodel_description,./plateau_uml_20240708_all_packages_export.xmi,lutaml_data_dictionary.yml]
----
[.diagram_include_block,base_path="./xmi-images",format="png"]
....
....
----
```

The plugin recognizes the two root packages, but they can't recurse into sub-packages.

* Clause 2 for package "CityGML 2.0" only has a listing. However, it did not recursively render each package inside and the diagrams inside.
<img width="422" alt="Screenshot 2024-07-13 at 10 12 40 AM" src="https://github.com/user-attachments/assets/eeb34683-3faf-4559-94c3-7c70f228645f">
<img width="319" alt="Screenshot 2024-07-13 at 10 14 14 AM" src="https://github.com/user-attachments/assets/89a7dcf1-eafb-424e-988a-2cf9909f6690">
* Clause 3 for package "i-UR" rendered 1 diagram, which is correct. It also did not recursively render the package inside.
<img width="595" alt="Screenshot 2024-07-13 at 10 25 10 AM" src="https://github.com/user-attachments/assets/c2024361-75e7-4e0e-a7ca-30f6fe2c67a6">
<img width="314" alt="Screenshot 2024-07-13 at 10 14 50 AM" src="https://github.com/user-attachments/assets/9420de6d-4535-4bbe-8a1b-c1c945495ac9">

My config YAML is:
```yaml
packages:
- CityGML2.0
- i-UR
```

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-plateau/issues/114#issuecomment-2226726013_

**Comment by kwkwan** [comment]
Sub-packages can be generated with the option `render_nested_packges`.

The attached file is the PDF output.
[001-mds.pdf](https://github.com/user-attachments/files/16262039/001-mds.pdf)

**Comment by kwkwan** [comment]
Closed as completed in https://github.com/metanorma/metanorma-plugin-lutaml/pull/125.
