### ISSUE TITLE
Create a block macro to render table of a class in plateau

### ISSUE THREAD

**Issue by kwkwan** [metanorma/metanorma-plugin-lutaml#140]
The table should show:

- its owned attributes
- its super class
- owned attributes of super class
- loop super class to get its super class till it is topmost
- owned attributes of these super classes

**Comment by kwkwan** [comment]
Refer to table in `4.18.3.1.1` `dem:ReliefFeature` (Plateau document 001-v4)

**Comment by ronaldtse** [comment]
@kwkwan can we loop till we get to the top superclass?

**Comment by kwkwan** [comment]
> @kwkwan can we loop till we get to the top superclass?

@ronaldtse Yes, it will.

**Comment by ReesePlews** [comment]
hello @kwkwan thanks for the work on the lutaml gml dictionary tool, it is working well.

regarding the example table, shown below

> Refer to table in `4.18.3.1.1` `dem:ReliefFeature` (Plateau document 001-v4)

is it possible to use a different table (shown below) for the initial test?
doc001-v4 - document page 58, pdf page 69.
4.2.3 建築物の応用スキーマ文書
Building （CityGML）
bldg:Building

i have prepared the most content (EA "Notes" property) for that subpackage tables.  thank you.

happy to test these updates when you are ready. just let me know.  thanks!

**Comment by kwkwan** [comment]
> hello @kwkwan thanks for the work on the lutaml gml dictionary tool, it is working well.
> 
> regarding the example table, shown below
> 
> > Refer to table in `4.18.3.1.1` `dem:ReliefFeature` (Plateau document 001-v4)
> 
> is it possible to use a different table (shown below) for the initial test? doc001-v4 - document page 58, pdf page 69. 4.2.3 建築物の応用スキーマ文書 Building （CityGML） bldg:Building
> 
> i have prepared the most content (EA "Notes" property) for that subpackage tables. thank you.
> 
> happy to test these updates when you are ready. just let me know. thanks!

OK.  I will switch the initial test to this example.

**Comment by kwkwan** [comment]
During the test with the example (`4.2.3 bldg:Building`) and xmi file `plateau_uml_20240708_all_packages_export.xmi`, I can retrieve the following properties in `継承する関連役割`:

```
lod0RoofEdge
address
boundedBy
lod2Solid
lod4Solid
lod1Solid
lod3Solid
bldg::lod2MultiSurface
lod0FootPrint
lod4MultiSurface
bldg::lod3MultiSurface
bldgDmAttribute
bldgDataQualityAttribute
largeCustomerFacilityAttribute
consistsOfBuildingPart
bldgDisasterRiskAttribute
ifcBuildingAttribute
bldgFacilityAttribute
bldgFacilityIdAttribute
bldgRealEstateIDAttribute
outerBuildingInstallation
bldgUsecaseAttribute
bldgKeyValuePairAttribute
buildingDetailAttribute
interiorRoom
indoorBuildingAttribute
buildingIDAttribute
bldgFacilityTypeAttribute
interiorBuildingInstallation
```

A property named `bldgUsecaseAttribute` is found but not in the PDF.  Is it correct to show it?

**Comment by ReesePlews** [comment]
hello @kwkwan since these tables in the document are "model driven" i think we should show the content from the model, as it may have been mistakenly left off in the PDF (because they were manually created). i think @ronaldtse would agree with this understanding.

**Comment by ReesePlews** [comment]
hello again @kwkwan if i wanted to confirm the version (date) of the XMI file, where should i look? want to make sure you have the newest version.

**Comment by kwkwan** [comment]
I download the xmi file `plateau_uml_20240708_all_packages_export.xmi` on 12 July 2014.  The size of it is 10.6 MB.

**Comment by ReesePlews** [comment]
there is a newer version, how can i get that to you?

**Comment by ronaldtse** [comment]
I have just uploaded it to this commit:
* https://github.com/metanorma/mn-samples-plateau/pull/114/commits/6a041dcdb50ef48aad620d7addcb646f52ae27fd

@kwkwan can you try with the newly exported XMI file? It seems to contain additional GML content.

**Comment by ReesePlews** [comment]
thanks @ronaldtse

**Comment by ReesePlews** [comment]
@kwkwan if you have any questions about the new version, please let me know. the structure has changed, with the figures now inside of the individual folders, instead of outside.

**Comment by kwkwan** [comment]
When generating the table for class. some attributes shown in PDF are still missing in the new macro.  It is because I cannot find out the logical to get these attributes from `Building`.

These attributes are:
 - `gml` and `core in 継承する属性
- `gen` in 継承する関連役割

@ronaldtse Do you have any cues to link up the these attributes with `Building`?

**Comment by ReesePlews** [comment]
hello @kwkwan because the UML tables in doc01 were made manually, there are attributes which are not readily accessible (through the model), in my understanding.  the inherited attribute cells that are "gray" in color were manually added to those tables and are not in the individual models. are those the attributes you are mentioning?

@ronaldtse and i have discussed with the client, and at this time, we can leave out the attributes from the gray cells if they are not already linked in the UML, unless Ron has directed you to do something different. i am not really the UML expert. 

does that help?

**Comment by ronaldtse** [comment]
@kwkwan can you please post the exact attributes/relationships that are missing and from which class?

**Comment by kwkwan** [comment]
OK.  Here they are.
<img width="1241" alt="Screenshot 2024-09-03 at 3 13 49 PM" src="https://github.com/user-attachments/assets/4dca97f2-acbc-4de6-bdbb-99ee752d5e86">

<img width="1241" alt="Screenshot 2024-09-03 at 3 14 44 PM" src="https://github.com/user-attachments/assets/189e91c2-1277-437f-8393-871e8d6a3124">

**Comment by ronaldtse** [comment]
Update: I did some digging on the 2nd category, with `dateAttribute`. Unfortunately, I cannot find **any** connection between `Building` and `dateAttribute` in the XMI. They should not exist in the table?

**Comment by ReesePlews** [comment]
hello @kwkwan looks like you are using the HTML output, please use the PDF, the official file plateau_doc_0001_ver04.pdf from the "reference-docs" folder. it will have gray shaded tables
i will paste in here

**Comment by ReesePlews** [comment]
![image](https://github.com/user-attachments/assets/7be9f161-17c0-4d20-9854-5dda0f894a0d)

![image](https://github.com/user-attachments/assets/cc2faa29-738c-40a4-88b4-fd6783ea4edf)

please see the pdf for the remaining parts of the table

**Comment by ronaldtse** [comment]
As previously agreed, things that cannot be determined from the model must be dropped.

This includes:
* gray shading and the parentheses because whether an attribute is meant to be used is not shown in the table.

**Comment by ReesePlews** [comment]
@ronaldtse yes, correct "gray shading" content will not be in the model. but i dont know why i cannot find gml:description, its not shaded gray.

**Comment by ReesePlews** [comment]
maybe it comes from gml:feature? 

![image](https://github.com/user-attachments/assets/92e53d75-a524-4618-859e-7bd9d25254be)

**Comment by ronaldtse** [comment]
> maybe it comes from gml:feature?

Yes it is:
```xml
				<packagedElement xmi:type="uml:Class" xmi:id="EAID_553A3DF9_69B8_4fb4_BF15_EC613B5B74CD" name="_Feature" isAbstract="true">
					<ownedAttribute xmi:type="uml:Property" xmi:id="EAID_E52C9299_7D96_49e8_B6E1_B81E93B8C25F" name="boundedBy">
```

This means all classes that inherit from `_Feature` shall also have this attribute.

However, the only classes that inherit from `_Feature (id: EAID_553A3DF9_69B8_4fb4_BF15_EC613B5B74CD)` in the XMI are:
* `_CityObject`
* `Address`
* `Appearance`
* `_FeatureCollection`

i.e. this is "meant to come from _Feature", but there doesn't seem to be any connection between `_Feature` and the `Building` class in the model.

**Comment by ronaldtse** [comment]
@kwkwan can you update the table to show for each inherited attribute/association, from which class it is inherited from? This will help the reader.

**Comment by kwkwan** [comment]
@ronaldtse Updated tables to show where the attributes come from via commit (84dddd3f574e600f7569b0227417900e822cbf97).  Those attributes are all from `_AbstractBuilding` as no attribute has been defined in `Building` class.

**Comment by ReesePlews** [comment]
hello @kwkwan thank you for the code to show the sample. 

i have a question about the content which is stored in the EA "Notes Property". 
when adding content to the components of the model in EA, for "building" i used the model on docpage47, pdf page 58 of the original  doc01-v4.pdf ; i have added content to as many components (classes, attributes, roles, etc) as i could.

for "inherited roles" (継承する関連役割) i have added content which should be showing in the "definition" (定義) column of the autogenerated table. in my locally generated version of the document, i am not seeing that content. 

(lutaml autogenerated plateau uml table): 
![image](https://github.com/user-attachments/assets/c1fc26fe-ef18-4ed4-a8de-0f7d1bcf51d2)

however for bldg:lod1Solid (and other inherited roles) i have pasted their content into the "Notes Property"

![image](https://github.com/user-attachments/assets/05592405-cea6-413a-8394-cc1f27e1938a)

are you seeing that content in the XMI file or is it missing? perhaps you just have not added that content to the table yet.  i just wanted to mention this.

**Comment by ronaldtse** [comment]
I believe we haven’t added these content to our model. @kwkwan can you please help include them?

**Comment by kwkwan** [comment]
OK.  I will follow up this issue.

**Comment by ReesePlews** [comment]
thank you for checking that @kwkwan . i noticed something else, the order of the content in the autogenerated tables (attributes, roles, etc) does not seem to match the order of the original table. are you modifying the order, or is it exactly from the XMI file? if the order is exactly from the XMI file, then i need to ask the client where they set the order of the "things" in the model (in EA). sorry i forgot to mention this earlier.

**Comment by kwkwan** [comment]
> OK. I will follow up this issue.

The gem `lutaml` has been updated to show the definitions from connectors via associations.

**Comment by ReesePlews** [comment]
thank you very much @kwkwan i will regenerate the document from now.

**Comment by kwkwan** [comment]
> thank you for checking that @kwkwan . i noticed something else, the order of the content in the autogenerated tables (attributes, roles, etc) does not seem to match the order of the original table. are you modifying the order, or is it exactly from the XMI file? if the order is exactly from the XMI file, then i need to ask the client where they set the order of the "things" in the model (in EA). sorry i forgot to mention this earlier.

The order follows the content in XMI file.

**Comment by ReesePlews** [comment]
> The gem `lutaml` has been updated to show the definitions from connectors via associations.

thank you @kwkwan the 2nd build of the document showed the content for the associations.

**Comment by kwkwan** [comment]
Discussed with @ronaldtse, attributes are now sorted by name.

**Comment by ReesePlews** [comment]
hello @kwkwan i have a new version of the model.  an abstract class and relationships were missing and have been added. i also have feedback on the table style. how can i send you the model, make a new folder and submit via github desktop?

**Comment by kwkwan** [comment]
You can submit the the file to the folder `reference-docs` of the repo `mn-sample-plateau` via github desktop.

**Comment by ReesePlews** [comment]
https://github.com/metanorma/mn-samples-plateau/commit/d178776ac6dfc7cdada96638b98547eb3a7b70d6

sorry @kwkwan could not upload to reference-docs; see the note with the commit. thank you.

**Comment by kwkwan** [comment]
Hi @ReesePlews I have received the file.  Thank you.

**Comment by ReesePlews** [comment]
hello @kwkwan the structure and style of the table looks good. at this time there is one item i wondered if you could adjust.

![image](https://github.com/user-attachments/assets/c4a5d629-9409-49fb-9e7d-de3ece5a7c0a)

in the cell on the left, the attribute `bldg:roofType (_AbstractBuilding)`. while the content is a bit different from the original table we like the additional information shown in the ( )s.  however the data is shown as one continuous line, i wonder if it is possible to put a carriage return after the initial attribute name. something like this:

```
bldg:roofType
(_AbstractBuilding)
```
i think it would be easier to read. if that is a lot of work please discuss with @ronaldtse. thank you.

**Comment by kwkwan** [comment]
Carriage return has been added after the attribute name.

**Comment by ReesePlews** [comment]
hello @kwkwan i have checked the carriage returns in the table and they look good. thank you.

i have also updated the model with the content data from the "landuse" classes.  that is described here: https://github.com/metanorma/mn-samples-plateau/pull/114/commits/6a3801951b97af352b67e69fe2ae1e414b66b72b

i tried to generate the document locally after adding content for the landuse i am not seeing that data output in the Landuse table. i also updated the first row of the building table with content but it was not shown either.

after checking the xmi output, let me know if you find any problems with that. thank you

**Comment by ReesePlews** [comment]
hello @kwkwan thank you for updating the model. i have checked the output and i have two questions:

1) in the Landuse model, i added "content" into the "Notes properties" for the attributes after the "⾃⾝に定義された属性" heading (example "areaClassificationType") but that content is not showing in the autogenerated table. 

![image](https://github.com/user-attachments/assets/6fec9744-d719-493e-bac9-ecf5f2fd4b2b)

2) in the Building model i added "content" into the "Notes properties" for the _AbstractBuilding class, not only the individual attributes.  i was expecting that content to be displayed in the first row of the autogenerated table, in the cell to the right of "型の定義", similar to what is shown on doc01-v4, pg 58, pdf pg69, but that cell is still empty.

![image](https://github.com/user-attachments/assets/f88e40a0-0cb0-4e73-a0f3-f6195f71886f)


i added that new "content" in the building model "Notes property" to test the formatting described in (https://github.com/metanorma/coradoc/issues/125)  ;   these updates to the building model are the first which actually have an image correctly formatted.

if you could check into these two issues, i will provide feedback to help. thank you.

**Comment by ronaldtse** [comment]
For the second one, the note on AbstractBuilding will not show up because the table is for Building, not the superclass AbstractBuilding. 

The first one may be a bug.

**Comment by ReesePlews** [comment]
thanks @ronaldtse i also have contents pasted in for the "Building" class which is shown (without attributes) below the Abstract building class, if that information helps. the content is slightly different, but it can be unified. the content in the _Abstract building class would be "more correct" (as it was actually pulled from the static table that was created during the main conversion of the document.)

**Comment by ronaldtse** [comment]
I'm not sure if I'm confused, but no description for AbstractBuilding would be shown because there is no individual table for AbstractBuilding. A table will only show the description for that class.

**Comment by ReesePlews** [comment]
hi Ron, i thought bldg::_AbstractBuilding was a class in the model... so that is why i was able to attach "contents" in the "Notes Property" of the bldg::_AbstractBuilding; previously i had only attached the same content to the smaller bldg::Building class

![image](https://github.com/user-attachments/assets/942f8340-cd91-4280-9c8f-3167a34013e0)

**Comment by ronaldtse** [comment]
The `_AbstractBuilding` class is a class but it is **not rendered as a table** in this document. Therefore no description will show up in this document. This is a design decision of the PLATEAU team to not have individual tables for every class.

**Comment by ReesePlews** [comment]
thank you @ronaldtse for the clarification, that initial row will need to be styled either as a separate table or as normative body text.

**Comment by ReesePlews** [comment]
@kwkwan question 2) from earlier has been resolved.

**Comment by kwkwan** [comment]
> hello @kwkwan thank you for updating the model. i have checked the output and i have two questions:
> 
> 1. in the Landuse model, i added "content" into the "Notes properties" for the attributes after the "⾃⾝に定義された属性" heading (example "areaClassificationType") but that content is not showing in the autogenerated table.
> 

Hi @ReesePlews, for question 1, the attribute of `areaClassificationType` is belonged to `LandUseDetailAttribute` rather than `LandUse`.  So, the table will not show the content.

```
<element xmi:idref="EAID_38DBDE3D_DC81_4505_A700_7EC81CED4BD1" xmi:type="uml:Class" name="LandUseDetailAttribute" scope="public">
...
    <attributes>
      <attribute xmi:idref="EAID_FEE8895A_4DD1_4349_A3CD_9BA582E5DFEF" name="areaClassificationType" scope="Public">
        <documentation value="[format=asciidoc]&#xA;&#xA;[lang=jp]&#xA;== Content&#xA;&#xA;&#x571F;&#x5730;&#x304C;&#x5C5E;&#x3059;&#x308B;&#x533A;&#x57DF;&#x533A;&#x5206;&#x3002;&#x30B3;&#x30FC;&#x30C9;&#x30EA;&#x30B9;&#x30C8;(Common_areaClassificationType.xml)&#x3088;&#x308A;&#x9078;&#x629E;&#x3059;&#x308B;&#x3002;"/>
...
```

There is another attribute with the name `uro:areaClassificationType` which is belonged to `LandUse`.  If you update that attribute, the content should be shown in the table.  Currently, the content of it is empty.

```
 <packagedElement xmi:type="uml:Class" xmi:id="EAID_B34C7AA1_F3FD_42a0_A358_EAC39394782C" name="LandUse">
      <ownedAttribute xmi:type="uml:Property" xmi:id="EAID_01A977DA_3316_4599_9CDE_1FA18D8BCDAA" name="uro::areaClassificationType">
        <type xmi:idref="EAID_0F5E62CD_5DD3_4fc0_94FD_7FB26CD0807D"/>
        <lowerValue xmi:type="uml:LiteralInteger" xmi:id="EAID_LI002273_3316_4599_9CDE_1FA18D8BCDAA" value="0"/>
        <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="EAID_LI002274_3316_4599_9CDE_1FA18D8BCDAA" value="1"/>
      </ownedAttribute>
...
      <element xmi:idref="EAID_B34C7AA1_F3FD_42a0_A358_EAC39394782C" xmi:type="uml:Class" name="LandUse" scope="public">
        ...
      <attribute xmi:idref="EAID_01A977DA_3316_4599_9CDE_1FA18D8BCDAA" name="uro::areaClassificationType" scope="Public">
        <initial/>
        <documentation/>
...
```

**Comment by ReesePlews** [comment]
hello @kwkwan

i discussed this with the client and they understand that content from  `_AbstractBuilding` class will not appear in the table but there is also content for bldg::Building the class below  `_AbstractBuilding`. because the table is for bldg::Building, that content should appear in the right cell of the top row of the table. (as shown in the image)

![image](https://github.com/user-attachments/assets/7c3c37cd-d588-4d98-bef1-293683d9258f)

please tell me if that content accessible in the .xmi file?  thank you.

**Comment by kwkwan** [comment]
The name will be shown when the definition is not found.

**Comment by ronaldtse** [comment]
@kwkwan wait, this is not the right way of doing things.

The "型の定義" field is *only* supposed to show the definition of "bldg:Building". We should not insert the name "bldg:Building" or the definition of "bldg:_AbstractBuilding" here.

The EA model is now like this:
<img width="1911" alt="image" src="https://github.com/user-attachments/assets/56433faf-7fa2-462c-a575-b439f0e44235">

Therefore the text at the bottom right corner should be filled in "型の定義".

**Comment by ReesePlews** [comment]
@kwkwan let me double check the text in the file. i copy-pasted from another "Notes property" into the model, perhaps that is an issue.

**Comment by ronaldtse** [comment]
@kwkwan : the description given by @ReesePlews seems correct.

Can you help make sure this text ("居住その他の目的をもって構築された建築物。...") appears in the cell "型の定義" for "bldg:Building"?

Thanks.

**Comment by kwkwan** [comment]
@ReesePlews Updates the way to lookup definition by the `documentation` of `properties` under `element` when`documentation` under `attribute` is not found.

```
<element xmi:idref="EAID_B2D484B5_202B_4034_9046_90FCCEC07F56" xmi:type="uml:Class" name="Building" scope="public">
  <model package="EAPK_1D38D48C_F798_4ab9_AFDB_A6140AB461D4" tpos="0" ea_localid="63798" ea_eleType="element"/>
  <properties documentation="[format=asciidoc]&#xA;&#xA;[lang=jp]&#xA;== Content&#xA;&#xA;&#x5C45;&#x4F4F;&#x305D;&#x306E;&#x4ED6;&#x306E;&#x76EE;&#x7684;&#x3092;&#x3082;&#x3063;&#x3066;&#x69CB;&#x7BC9;&#x3055;&#x308C;&#x305F;&#x5EFA;&#x7BC9;&#x7269;&#x3002; &#xA;&#x666E;&#x901A;&#x5EFA;&#x7269;&#x3001;&#x5805;&#x308D;&#x3046;&#x5EFA;&#x7269;&#x3001;&#x666E;&#x901A
...
```

**Comment by kwkwan** [comment]
For example, `documentation` of `_AbstractBuilding` is stored like:
```
<xmi:Extension extender="Enterprise Architect" extenderID="6.5"></xmi:Extension>
<elements>
<element xmi:idref="EAID_6F915D44_6B5C_4298_891D_0FB0B1AF24F0" xmi:type="uml:Class" name="_AbstractBuilding" scope="public">
<attributes>
					<attribute xmi:idref="EAID_FDC435D4_544B_4122_BEA1_7C0B55136938" name="class" scope="Public">
						<initial/>
						<documentation value="[format=asciidoc]&#xA;&#xA;[lang=jp]&#xA;== Content&#xA;&#xA;&#x5EFA;&#x7BC9;&#x7269;&#x306E;&#x5F62;&#x614B;&#x306B;&#x3088;&#x308B;&#x533A;&#x5206;&#x3002;&#x30B3;&#x30FC;&#x30C9;&#x30EA;&#x30B9;&#x30C8;(&amp;lt;&amp;lt;Building_class.xml&amp;gt;&amp;gt;)&#x3088;&#x308A;&#x9078;&#x629E;&#x3059;&#x308B;&#x3002;"/>
...
```

**Comment by ronaldtse** [comment]
@kwkwan for `_AbstractBuilding -> class` it is actually an attribute called `class` with a description:
<img width="1271" alt="Screenshot 2024-09-13 at 11 36 16 AM" src="https://github.com/user-attachments/assets/c2fa4b12-d231-4e1b-bfb1-6c650504edb7">

The `_AbstractBuilding` definition is a separate location, I think as you mentioned under `element > properties[documentation]`:
<img width="1301" alt="Screenshot 2024-09-13 at 11 37 12 AM" src="https://github.com/user-attachments/assets/32b60d4c-9310-420f-91b1-919431bd8357">

**Comment by ReesePlews** [comment]
@kwkwan and @ronaldtse thank you for following up on this. i am sorry i am not understanding everything.

i select the individual classes (boxes) attributes and roles only on the model figures, then i update (paste) the content into the "Notes property". when i go to the non-figure browser, and press on "Building" i can see my content for the class (box) Building (in the image below). because the call to lutaml to render the table used Building 

`lutaml_klass_table::../../sources/001-mds/20240910_all_package_export_plus_new_tc211_gml.xmi[name="Building"]`

that is what i was expecting would be visible in the right cell of the first row of the Building table that lutaml is generating.   if my understanding is wrong, we will need to talk with the client. @ronaldtse if you have time today i will ask them if they can discuss. let me know offline. thanks

![image](https://github.com/user-attachments/assets/a650c497-ea02-4a6e-b7d0-048bfa30994d)

**Comment by kwkwan** [comment]
@ReesePlews Sorry to make you confused.  After discussed with @ronaldtse, this definition has been restricted to lookup the documentation from element properties.

i.e.
```
<element xmi:idref="EAID_B2D484B5_202B_4034_9046_90FCCEC07F56" xmi:type="uml:Class" name="Building" scope="public">
  <model package="EAPK_1D38D48C_F798_4ab9_AFDB_A6140AB461D4" tpos="0" ea_localid="63798" ea_eleType="element"/>
  <properties documentation="[format=asciidoc]&#xA;&#xA;[lang=jp]&#xA;== Content&#xA;&#xA;&#x5C45;&#x4F4F;&#x305D;&#x306E;&#x4ED6;&#x306E;&#x76EE;&#x7684;&#x3092;&#x3082;&#x3063;&#x3066;&#x69CB;&#x7BC9;&#x3055;&#x308C;&#x305F;&#x5EFA;&#x7BC9;&#x7269;&#x3002; &#xA;&#x666E;&#x901A;&#x5EFA;&#x7269;&#x3001;&#x5805;&#x308D;&#x3046;&#x5EFA;&#x7269;&#x3001;&#x666E;&#x901A
...
```

**Comment by ReesePlews** [comment]
thank you @kwkwan, am a UML beginner, so confusion problem is on me! i appreciate the patience from you and Ron! when you make any changes that you need me to check, just let me know. thanks for all the diligent work on this!

**Comment by ReesePlews** [comment]
hello @kwkwan and @ronaldtse 

i have generated the document locally after doing a "bundle update" the **very positive** results are shown below:

![image](https://github.com/user-attachments/assets/bf6b42d2-6cc2-408d-aac7-e27baebd10f2)
![image](https://github.com/user-attachments/assets/c2ebbb23-f19f-4fee-ae36-2e03c3740e3c)

it looks really good. thank you. even the other tables i have asked you to add the lutaml statement for are generating well. (but i still need to check them).

my next question would be the gray coloring of the cells and the rendering of the [Content] in those cells. should i discuss those things here, or a different issue, please advise.

**Comment by kwkwan** [comment]
Yes, I think we discuss them here.

**Comment by ReesePlews** [comment]
hello @kwkwan regarding the next questions:

Q1: gray background coloring of cells:

1. how can i style a single cell to be "gray"? 
2. would there be a way to indicate individually which cells in a row would be "gray"? like [cell1:rgb...]
because the content i made is placed into the right most cell, it would seem difficult (and possibly strange) to try and control the coloring of other cells when that content in those cells is automatically added. however, the client document colors the left most cells of certain entities as a way of communicating to the user.  i am wondering if it may be better to support [row:rgb] as a way to color the background of the current row? 

Q2: the current status of the content as asciidoc being read from the XMI file:

1. in the cells where i have added content, there are [_content_x] Content. i can understand the [_content_x] is perhaps debugging call but what about the other "Content", is that being interpreted as an asciidoc heading? 
there is a discussion [here](https://github.com/metanorma/coradoc/issues/127#issuecomment-2348562184).  

if you need me to modify the contents in the 3 tables we are checking please let me know.  thank you.

**Comment by kwkwan** [comment]
> Q1: gray background coloring of cells:
> 
> 1. how can i style a single cell to be "gray"?
> 2. would there be a way to indicate individually which cells in a row would be "gray"? like [cell1:rgb...]
>    because the content i made is placed into the right most cell, it would seem difficult (and possibly strange) to try and control the coloring of other cells when that content in those cells is automatically added. however, the client document colors the left most cells of certain entities as a way of communicating to the user.  i am wondering if it may be better to support [row:rgb] as a way to color the background of the current row? 

Hi @ReesePlews and @ronaldtse For the styling of the table, I think it can be changed by using standard asciidoc syntax.  However, the plugin will be needed to update to allow the user to specific the template path.

**Comment by ReesePlews** [comment]
thank you @kwkwan standard asciidoc syntax is important. we dont want to deviate from that. i could not find that asciidoc/asciidoctor supported such coloring except through the use of CSS. 

if the shading setup for the "dynamic content" (content which you parse from the .xmi file) is in the template, can it be called on a "cell by cell" or "row by row" basis... when it is needed?

for example in the original document the left most cells are shaded:
![image](https://github.com/user-attachments/assets/f0288181-9afe-447c-a9df-8d2ddea8825c)

in our autogenerated document:
![image](https://github.com/user-attachments/assets/9c5b3b58-040c-4974-9cda-18efb1e34da1)

i dont understand much with the template. i think you understand the issue here. a "work around" is also a possibility, such as "shading the row, not just the left most cell." please discuss these things with @ronaldtse at your earliest convenience. thank you.

**Comment by ronaldtse** [comment]
1. Shading of table cells are not allowed in Metanorma, because Metanorma is a semantic syntax. The way to shade a cell is to mark it as a heading cell (`h|`). According to our last discussion, the gray shading was to indicate which inherited cells are not used in the current class, and the team was fine to omit that?

2. The "content" issue will be handled by the Coradoc task of embedding AsciiDoc.

**Comment by ronaldtse** [comment]
@reeseplews can’t they use another way like an additional “star” or some indication for that purpose?

**Comment by ReesePlews** [comment]
hello @kwkwan earlier in this issue we talked about the order of how attributes, and other entities from the UML model (.xmi file) will be ordered in the table. is that a "switch" that the user can invoke when they make the call to lutaml or is that something hard coded into the code? 

i ask because i was told about a setting in EA that could be useful to this project.  in EA from the "Start > Preference pane (Preferences) > the dialogue below:

![image](https://github.com/user-attachments/assets/97d954aa-e193-4184-b3d7-6c0d3477a4c2)

let me know if i should make a new issue where i ask about this.  thank you,

**Comment by kwkwan** [comment]
Hi @ReesePlews Currently, the order of the attributes in the Class table is sorted by `name`.  If you want to change the type of `sort_by` or `order` (ascending or descending), please free feel to create new issue to further elaborate it.

**Comment by ReesePlews** [comment]
thank you @kwkwan , before i create a new issue to request some code enhancement, can you turn off the sort so that the original order from the .xmi file is used. this way we will know if there is an option in EA to handle or not. sorry to ask you to do that but i think better we test with it off at this time, and before any enhancement is requested. thank you.

**Comment by ReesePlews** [comment]
@kwkwan sorry i have another question. last month you updated branch 001-mds using the following code in the document.adoc file:

```
= Standard Data Product Specification for 3D City Model
:docnumber: 1
:edition: 4
:revdate: 2024-03-22
:published-date: 2024-03-22
:copyright-year: 2024
:language: ja
:title-intro-ja: 3D都市モデル導入のためのガイドブック
:title-main-ja: 3D都市モデル標準製品仕様書
:publisher: 国土交通省 都市局
:sponsor: （協力）内閣府 地方創生推進事務局
:title-intro-en: Handbook of 3D City Models
:title-main-en: Standard Data Product Specification for 3D City Model
:doctype: handbook
:coverpage-image: images/coverpage.png
:imagedir: images
:mn-document-class: plateau
// :mn-output-extensions: doc,xml,html,pdf,rxl
:mn-output-extensions: html,pdf
:local-cache-only:
:data-uri-image:

include::sections/abstract-01.adoc[]

include::sections/abstract-02.adoc[]

include::sections/section-01.adoc[]

// TODO: This section fails when parsing the XMI due to "GML" issues
[[conceptual-model]]
[lutaml_uml_datamodel_description,./plateau_uml_20240708_all_packages_export.xmi,lutaml_data_dictionary.yml]
----
[.diagram_include_block,base_path="./xmi-images",format="png"]
....
....
----


include::sections/bibliography-01.adoc[]

include::sections/appendix-A.adoc[]
```

which autogenerated all of the tables from the .xmi for testing purposes (but not the other parts of the document).

i tried to run it yesterday but i did not work. ran for a few hours. i think because of the change to lutaml_klass_table that document no longer is generating the previous output?

if this is a minor change, can you update that so it auto generates all of the tables like it was doing a month back?

if this requires an enhancement, please discuss with @ronaldtse first. 

i will send a new .xmi file later today. the content of the "Notes property" has been simplified.  thank you.

**Comment by kwkwan** [comment]
> thank you @kwkwan , before i create a new issue to request some code enhancement, can you turn off the sort so that the original order from the .xmi file is used. this way we will know if there is an option in EA to handle or not. sorry to ask you to do that but i think better we test with it off at this time, and before any enhancement is requested. thank you.

I will turn off the sorting to allow it follows original order in xmi.  (https://github.com/lutaml/lutaml/issues/88)

**Comment by kwkwan** [comment]
> @kwkwan sorry i have another question. last month you updated branch 001-mds using the following code in the document.adoc file:
> 
> which autogenerated all of the tables from the .xmi for testing purposes (but not the other parts of the document).
> 
> i tried to run it yesterday but i did not work. ran for a few hours. i think because of the change to lutaml_klass_table that document no longer is generating the previous output?
> 
> if this is a minor change, can you update that so it auto generates all of the tables like it was doing a month back?
> 
> if this requires an enhancement, please discuss with @ronaldtse first.
> 
> i will send a new .xmi file later today. the content of the "Notes property" has been simplified. thank you.

I have update the document in `001-mds` via https://github.com/metanorma/mn-samples-plateau/pull/114/commits/dffcbf9e799c02b768eeb9bbac4a094e3402972f.  Please try again to regenerate the document in `001-mds`.
