### ISSUE TITLE
Misparsing of `[0..1]`

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-lutaml#20]
There is a sample file being tested in metanorma-standoc, spec/fixtures/diagram_definitions.lutaml

It contains

````
    imlicistAttributeProfile: CharacterString [0..1] {
````

It is supposed to be generating in lutaml, in the "Mandatory/ Optional/ Conditional" column:

````
 <td valign='top' align='left'>O</td>
````

but now it is generating

````
 <td valign='top' align='left'>M</td>
````

This is blocking release of the gem.

**Comment by w00lf** [comment]
@opoudjis fixed in lutaml 0.5.2
