### ISSUE TITLE
Github actions setup is missing graphviz` dot command install

### ISSUE THREAD

**Issue by w00lf** [metanorma/metanorma-plugin-lutaml#22]
https://github.com/metanorma/metanorma-plugin-lutaml/runs/2113632738?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1158036/111208372-b40cc580-85db-11eb-9525-cac33c69c19f.png)
@CAMOBAP can you help with this one?

**Comment by CAMOBAP** [comment]
@w00lf sorry, overlooked. Now should be fixed
