### ISSUE TITLE
lutaml_uml_datamodel_description macro

### ISSUE THREAD

**Issue by w00lf** [metanorma/metanorma-plugin-lutaml#34]
We need to create a new macro for generating datamodel ascidoc code similar to the one used in https://github.com/metanorma/ogc-citygml-xmi/issues/1 in lutaml macro. Proposed format:
```adoc
[lutaml_uml_datamodel_description, /path/to/file.xmi, /path/to/config.yml]
--
[.preface]
---
some text
---

[.footer]
---
My custom footer text
--- 
--
```

Where:
- `/path/to/file.xmi` - required, path to uml datamodel xmi file
- `/path/to/config.yml` - optional, path to special yaml config file, look below for format
- block text, `.preface`, `.footer` macroses - optional, sets predefined text to be inserted into the temaplte during render, `.preface` and `.footer` is just an example of naming, TODO: define actual blocks

The above-mentioned macro need to use supplied xmi file and generate adoc code similar to the one used here - https://github.com/metanorma/ogc-citygml-xmi/blob/master/sources/standard/_packages.liquid and insert into the document.

**Yaml config file.**

Additional config file used to tell the parser what packages to use in the render and in what order, also it can hold packages to skip. 

example:

```yaml
packages_to_render:
  - one
  - two*
  - skip: three
  - four
```

- `packages_to_render` - main attribute, need to be a list of string/objects. Each string interpreted as a pattern that will be used to select packages can have a wildcard - `*` in order to match multiply packages. In order to skip some packages one can use an object instead of a string: `skip: three*`, each object will be taken and matched against package name and if pattern matches it will skip it.

**Comment by ronaldtse** [comment]
I think at the current point we can use a YAML file like this:

```yaml
packages:
  # includes these packages
  - "Package *"
  - two*
  - three
  # skips these packages
  - skip: four
```

```
[lutaml_uml_datamodel_description, /path/to/file.xmi, /path/to/config.yml]
--
[.before,package="Package 1"]
---
Text before Package 1
---

[.after,package="Package 2"]
---
Text after Package 2
--- 
--
```

**Comment by w00lf** [comment]
@ronaldtse implemented in #35

**Comment by w00lf** [comment]
Implement support for xmi file diagrams lookup. Example of diagram ref in requirement file - https://raw.githubusercontent.com/metanorma/ogc-dggs-xmi/feature/lutaml_uml_datamodel_description/sources/as21-dggs/requirements/_temporal_geometry_and_topology.adoc?token=AAI2XFBA62KNW4HLX5A6GXLBCEDPW. Proposed syntax:
```
lutaml-figure:[name="Fig: Primitives of Zonal Identifier"]
```
Eg: use diagram name as a lookup id and transform it into <<figure-{{ diagram.xmi_id}}>>(EA names diagram images by this pattern)

**Comment by ronaldtse** [comment]
For the record with @w00lf we've also discussed:

>Because lutaml programmatically generates content, you can generate attributes like:
> 
> `:figure-MyFigureName: EAID_C2D34AA2_FF6B_4b2d_BF51_89A80AE81170`
>
> Then in asciidoc you can retrieve it via:
> 
> `This is my ID {figure-MyFigureName}`

**Comment by ronaldtse** [comment]
This is implemented. Thanks @w00lf .
