### ISSUE TITLE
Support `.before` and `.after` for "each package", support Liquid interpolation as option

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#48]
With the CityGML document, an `[.after]` that means "after each class" will be very useful.

Right now we need to do this:

```
[.after, package="Bridge"]
....
==== Additional Information

Additional information about the Bridge Module can be found in the link:http://docs.opengeospatial.org/DRAFTS/20-066.html#ug-model-bridge-section[OGC CityGML 3.0 Users Guide]
....

[.after, package="Building"]
....
==== Additional Information

Additional information about the Building Module can be found in the link:http://docs.opengeospatial.org/DRAFTS/20-066.html#ug-model-building-section[OGC CityGML 3.0 Users Guide]
....


...
```

But we can instead do this:

```
[.after, each]
....
==== Additional Information

Additional information about the {{ package.name }} Module can be found in the link:http://docs.opengeospatial.org/DRAFTS/20-066.html#ug-model-{{package_name}}-section[OGC CityGML 3.0 Users Guide]
....
```

**Comment by w00lf** [comment]
Also add support for liquid interpolation in mentioned above macorses

**Comment by ronaldtse** [comment]
For interpolation, we want to have the option to 'enable' it explicitly, because normally `{{ term }}` means an index term in Metanorma, but in Liquid the same syntax is for interpolation.

To reference a Metanorma index term in a liquid template we need to escape using `{% raw %}`:
https://stackoverflow.com/questions/3330979/outputting-literal-curly-braces-in-liquid-templates

e.g. 
```
[.after,each,liquid="true"]
--
==== Additional Information

Additional information about the {{ package.name }} Module can be found in the
link:http://docs.opengeospatial.org/DRAFTS/20-066.html#ug-model-{{package_name}}-section[OGC CityGML 3.0 Users Guide]

--
```

**Comment by ronaldtse** [comment]
I think we should support `liquid=true` for all `.package_text` and `.include_block` as well.

**Comment by w00lf** [comment]
Implemented in https://github.com/metanorma/metanorma-plugin-lutaml/pull/62
