### ISSUE TITLE
Make `[lutaml,{filename}]` autodetect the model file type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#53]
We support
* `*.exp` files
* `*.xmi` files
* `*.lutaml` files

The author should not need to remember to write `[lutaml_express,foo.exp,options]` but should just work with `[lutaml,foo.exp,options]`.

**Comment by w00lf** [comment]
> We support
> 
> * `*.exp` files
> * `*.xmi` files
> * `*.lutaml` files
> 
> The author should not need to remember to write `[lutaml_express,foo.exp,options]` but should just work with `[lutaml,foo.exp,options]`.

@ronaldtse we already support that by default, lutaml determines parser by given file extention

**Comment by ronaldtse** [comment]
@w00lf that's great, but I might have broken it in #52 ... Can you help check? Thanks!

**Comment by w00lf** [comment]
@ronaldtse implemented in #72
