### ISSUE TITLE
Indentation of headings in remarks

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-lutaml#7]
Remarks contain Asciidoctor headings; e.g.

````
== General 

The subject of the *action_schema* is the description of actions,
the reasons for these actions, and the status of these actions.
````

Lutaml inserts those remarks as is, but they will almost always be inside clauses or subclauses of a document; e.g. in annotated-express,

````
[lutaml, ../../../resources/action_schema/action_schema.exp, repo]
---
{% for schema in repo.schemas %}
=== {{ schema.id }}

[source]
--
{{ schema.sourcecode }}
--

{{ schema.remarks }}
````

But that means that any heading within schema.remarks needs to be indented as at least `====`:

____
1. Schemas
1.1 action_schema
1.1.1 General
____

In the example above, `== General` must be converted to `==== General`. If we do not manipulate the indentation of headers, `General` gets added in instead as a top level clause (as it is in the source remark): "2. General"

This is an issue for asciidoctor includes, and it is addressed there with the leveloffset parameter: https://docs.asciidoctor.org/asciidoc/latest/directives/include-with-leveloffset/

So `include::chapter01.adoc[leveloffset=+1]` means insert the text of chapter01.adoc into the current document, but add one `=` to any heading in the text. (Headings are identified as `\n=+ `.)  `include::chapter01.adoc[leveloffset=-1]` means insert the text of chapter01.adoc into the current document, but remove one `=` from any heading in the text.

We require the same to be done with lutaml remarks. If leveloffset is present as an argument to the Lutaml macro, then we want that number of equal signs added or subtracted from any headings in any asciidoctor (remarks) imported.

So in annotated-express,  we will want lutaml invoked as:

`[lutaml, ../../../resources/action_schema/action_schema.exp, repo, leveloffset=+2]`

for the headings in the remarks to be nested correctly.

**Comment by ronaldtse** [comment]
> But that means that any heading within schema.remarks needs to be indented as at least ====:

@opoudjis what does that mean?

**Comment by opoudjis** [comment]
It's the indentation of imported headings to match their context: an h1 heading imported into a subclause has to be converted into an h3 heading.

**Comment by opoudjis** [comment]
This has been done successfully, closing.
