### ISSUE TITLE
Add auto-release mechanism to Rubygems

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#76]

**Comment by CAMOBAP** [comment]
@ronaldtse should it listen to some upstream repo? or just workflow that listen for tags and allow manual release?

**Comment by ronaldtse** [comment]
Just tags and release. Thanks!

**Comment by CAMOBAP** [comment]
Done

**Comment by ronaldtse** [comment]
Thanks!
