### ISSUE TITLE
Broken release workflow for v0.4.16

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#87]
The build workflow is not working and not releasing:
https://github.com/metanorma/metanorma-plugin-lutaml/actions/runs/2978020038

**Comment by CAMOBAP** [comment]
Fixed. The issue was with inaccessible METANORMA_PAT token (because of generic workflow). But it will be overkill to allow access to PAT for all repos (most of them even don't need it)

So for now we use METANORMA_PAT only if it available
