### ISSUE TITLE
EXPRESS: FUNCTION blocks are lost in rendering

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-plugin-lutaml#99]
# Description

`FUNCTION` blocks like this, for example:

```express
FUNCTION distance_between_cartesian_points(pt1, pt2 : cartesian_point) :
length_measure;

LOCAL
  temp_dis : length_measure;
END_LOCAL;

  temp_dis := SQRT ( ((pt1.coordinates[1]-pt2.coordinates[1])**2)
                    +((pt1.coordinates[2]-pt2.coordinates[2])**2) );

  RETURN(temp_dis);

END_FUNCTION;
```

are not showing up in rendering through the `[lutaml,...]` macro.

# To reproduce

You can compile the ISO 10303-112 document found in `data/documents/` of this PR: https://github.com/metanorma/iso-10303-detached-docs/pull/197

**Comment by ronaldtse** [comment]
@manuelfuenmayor can you confirm that this is a real issue in the annotated-express repo? 

This is because this current repo and the annotated-express repo use different rendering templates.

**Comment by ronaldtse** [comment]
Also, this issue seems to be an issue of the detached-docs repo, not a problem of the plugin itself.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, you are completely right. It is, in fact, a liquid code issue. The schema file lacks the code for fetching `FUNCTION` blocks. I think I can solve it. Thanks!
